name:                multidir
version:             0.1.0.0
github:              "jcranch/multidir"
license:             BSD-3-Clause
author:              "James Cranch"
maintainer:          "cranch@cantab.net"
copyright:           "James Cranch 2025"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Simple tool for running commands in multiple directories
category:            Command Line Tools
description:         Please see the README on GitHub at <https://github.com/jcranch/multidir#README>

dependencies:
- base >= 4.7 && < 5
- cond >= 0.5 && < 0.6
- containers >= 0.7 && < 0.8
- directory >= 1.3 && < 1.4
- filepath >= 1.5 && < 1.6
- filepattern >= 0.1.3 && < 0.2
- optparse-applicative >= 0.18.1 && < 0.19
- process >= 1.6 && < 1.7
- text >= 2.1 && < 2.2
- toml-reader >= 0.2.1 && < 0.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:         src
  ghc-options:
  - -fprint-potential-instances
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wwarn=missing-home-modules

executables:
  muld:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multidir

tests:
  Muld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wwarn=missing-home-modules
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multidir
    - HUnit        >= 1.6     && < 1.7
    - hspec        >= 2.7     && < 2.12
